version: "3.8"
services:
  db:
    image: postgres:17.6
    container_name: orthonyx_db
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 2s
      retries: 10
    networks:
      - orthonyx_network

  app:
    build: .
    container_name: orthonyx_app
    env_file:
      - .env.app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - orthonyx_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  orthonyx_network:
    driver: bridge

volumes:
  db_data: